baseURL = 'https://Lemur027.github.io/cyberbezpeka/'
languageCode = 'uk-ua'
title = 'Кібербезпека UA'
theme = 'PaperMod'

[params]
  defaultTheme = 'auto' # Тема підлаштовуватиметься під систему користувача (світла/темна)
  ShowPostNavLinks = true
  
[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Фільтри (Теги)"
    url = "/tags/"
    weight = 10
	
[params.cover]
hiddenInList = false
hiddenInSingle = false
